CREATE TABLE IF NOT EXISTS people
(
    id   INTEGER PRIMARY KEY,
    name VARCHAR(32) NOT NULL,
    born SMALLINT
);

CREATE TABLE IF NOT EXISTS movies
(
    id       INTEGER PRIMARY KEY,
    title    VARCHAR(64) NOT NULL,
    tagline  VARCHAR(256),
    released SMALLINT
);

CREATE TABLE IF NOT EXISTS movie_actors
(
    person_id INTEGER NOT NULL REFERENCES people (id),
    movie_id  INTEGER NOT NULL REFERENCES movies (id),
    role      VARCHAR(64) NOT NULL,
    PRIMARY KEY (person_id, movie_id, role)
);

INSERT INTO people (id, name, born) VALUES
(1,  'Keanu Reeves',        1964),
(2,  'Laurence Fishburne',  1961),
(3,  'Carrie-Anne Moss',    1967),
(4,  'Hugo Weaving',        1960),
(5,  'Tom Hanks',           1956),
(6,  'Robin Wright',        1966),
(7,  'Gary Sinise',         1955),
(8,  'Meg Ryan',            1961),
(9,  'Tom Cruise',          1962),
(10, 'Jack Nicholson',      1937),
(11, 'Demi Moore',          1962),
(12, 'Kevin Bacon',         1958),
(13, 'Kiefer Sutherland',   1966),
(14, 'Cuba Gooding Jr.',    1968),
(15, 'Kelly McGillis',      1957),
(16, 'Val Kilmer',          1959),
(17, 'Anthony Edwards',     1962),
(18, 'Tom Skerritt',        1933),
(19, 'Meg Ryan',            1961),
(20, 'Renee Zellweger',     1969),
(21, 'Matt Damon',          1970),
(22, 'Ben Affleck',         1972),
(23, 'Robin Williams',      1951),
(24, 'Minnie Driver',       1970),
(25, 'Stellan Skarsgard',   1951),
(26, 'Russell Crowe',       1964),
(27, 'Joaquin Phoenix',     1974),
(28, 'Connie Nielsen',      1965),
(29, 'Oliver Reed',         1938),
(30, 'Brad Pitt',           1963),
(31, 'Edward Norton',       1969),
(32, 'Helena Bonham Carter',1966),
(33, 'Meat Loaf',           1947),
(34, 'Jared Leto',          1971),
(35, 'Bruce Willis',        1955),
(36, 'Samuel L Jackson',    1948),
(37, 'Uma Thurman',         1970),
(38, 'John Travolta',       1954),
(39, 'Harvey Keitel',       1939),
(40, 'Tim Roth',            1961),
(41, 'Amanda Plummer',      1957),
(42, 'Ving Rhames',         1959),
(43, 'Eric Stoltz',         1961),
(44, 'Rosanna Arquette',    1959),
(45, 'Christopher Walken',  1943),
(46, 'Morgan Freeman',      1937),
(47, 'Gene Hackman',        1930),
(48, 'Al Pacino',           1940),
(49, 'Diane Keaton',        1946),
(50, 'Robert De Niro',      1943),
(51, 'Ray Liotta',          1954),
(52, 'Joe Pesci',           1943),
(53, 'Lorraine Bracco',     1954),
(54, 'Paul Sorvino',        1939),
(55, 'Sigourney Weaver',    1949),
(56, 'Michael Biehn',       1956),
(57, 'Lance Henriksen',     1940),
(58, 'Bill Paxton',         1955),
(59, 'Arnold Schwarzenegger',1947),
(60, 'Linda Hamilton',      1956),
(61, 'Robert Patrick',      1958),
(62, 'Edward Furlong',      1977),
(63, 'Harrison Ford',       1942),
(64, 'Sean Connery',        1930),
(65, 'Cate Blanchett',      1969),
(66, 'Ian McKellen',        1939),
(67, 'Elijah Wood',         1981),
(68, 'Orlando Bloom',       1977),
(69, 'Viggo Mortensen',     1958),
(70, 'Liv Tyler',           1977),
(71, 'Andy Serkis',         1964),
(72, 'John Hurt',           1940),
(73, 'Anthony Hopkins',     1937),
(74, 'Jodie Foster',        1962),
(75, 'Scott Glenn',         1941),
(76, 'Ted Levine',          1957),
(77, 'Gary Oldman',         1958),
(78, 'Tommy Lee Jones',     1946),
(79, 'Will Smith',          1968),
(80, 'Linda Fiorentino',    1960),
(81, 'Vincent D''Onofrio',  1959),
(82, 'Denzel Washington',   1954),
(83, 'Ethan Hawke',         1970),
(84, 'Angela Bassett',      1958),
(85, 'Whitney Houston',     1963),
(86, 'Clint Eastwood',      1930),
(87, 'Gene Hackman',        1930),
(88, 'Morgan Freeman',      1937),
(89, 'Richard Harris',      1930),
(90, 'Judi Dench',          1934),
(91, 'Pierce Brosnan',      1953),
(92, 'Michelle Yeoh',       1962),
(93, 'Jonathan Pryce',      1947),
(94, 'Halle Berry',         1966),
(95, 'John Cleese',         1939),
(96, 'Rosamund Pike',       1979),
(97, 'Sophie Marceau',      1966),
(98, 'Robert Carlyle',      1961),
(99, 'Denise Richards',     1971),
(100,'Judi Dench',          1934);

INSERT INTO movies (id, title, tagline, released) VALUES
(1,  'The Matrix',                  'Welcome to the Real World',                          1999),
(2,  'The Matrix Reloaded',         'Free your mind',                                     2003),
(3,  'The Matrix Revolutions',      'Everything that has a beginning has an end',         2003),
(4,  'The Devil''s Advocate',       'Evil has its winning ways',                          1997),
(5,  'A Few Good Men',              'In the heart of the nation''s capital...',           1992),
(6,  'Top Gun',                     'I feel the need, the need for speed!',               1986),
(7,  'Jerry Maguire',               'The rest of his life begins now.',                   1996),
(8,  'Stand By Me',                 'For some, it''s the last real taste of innocence',  1986),
(9,  'As Good as It Gets',          'A comedy from the heart that goes for the throat',  1997),
(10, 'What Dreams May Come',        'After life there is more. The end is just the beginning.', 1998),
(11, 'Snow Falling on Cedars',      'First loves. Last rights.',                          1999),
(12, 'You''ve Got Mail',            'At odds in life... in love on-line.',                1998),
(13, 'Sleepless in Seattle',        'What if someone you never met...',                   1993),
(14, 'Joe Versus the Volcano',      'A story of love, lava and burning desire.',          1990),
(15, 'When Harry Met Sally',        'Can two friends sleep together and still love each other in the morning?', 1989),
(16, 'That Thing You Do',           'In every life there comes a time when that thing you dream becomes that thing you do', 1996),
(17, 'The Polar Express',           'This Holiday Season... Believe',                     2004),
(18, 'Cast Away',                   'At the edge of the world, his journey begins.',      2000),
(19, 'Apollo 13',                   'Houston, we have a problem.',                        1995),
(20, 'The Green Mile',              'Miracles do happen.',                                1999),
(21, 'Forrest Gump',                'Life is like a box of chocolates...',               1994),
(22, 'Philadelphia',                'No one would take on his case... until one man was willing to take on the system.', 1993),
(23, 'The Da Vinci Code',           'Seek The Truth',                                     2006),
(24, 'Cloud Atlas',                 'Everything is connected',                            2012),
(25, 'Charlie Wilson''s War',       'A stiff drink. A little mascara. A lot of nerve.',  2007),
(26, 'The Birdcage',                'Come as you are',                                    1996),
(27, 'Unforgiven',                  'Some legends will never be forgotten. Some will.',   1992),
(28, 'Johnny Mnemonic',             'The hottest data on earth. In the coolest head in town.', 1995),
(29, 'The Replacements',            'Pain heals. Chicks dig scars. Glory lasts forever.', 2000),
(30, 'Twister',                     'Don''t breathe. Don''t look back.',                 1996),
(31, 'Bicentennial Man',            '...One robot''s 200 year journey to become an ordinary man.', 1999),
(32, 'A League of Their Own',       'Once in a lifetime you get a chance to do something different.', 1992),
(33, 'The Shining',                 'The tide of terror that swept America is here.',     1980),
(34, 'Five Easy Pieces',            '',                                                    1970),
(35, 'One Flew Over the Cuckoo''s Nest', 'If he''s crazy, what does that make you?',    1975),
(36, 'Terms of Endearment',         'Come to laugh, come to cry, come to care, come to terms.', 1983),
(37, 'The Bucket List',             'Find the joy.',                                      2007),
(38, 'Something''s Gotta Give',     '',                                                   2003),
(39, 'Hoffa',                       '',                                                   1992),
(40, 'Pulp Fiction',                'Just because you are a character doesn''t mean you have character.', 1994),
(41, 'Reservoir Dogs',              'Every dog has his day.',                             1992),
(42, 'Kill Bill Vol 1',             'Here comes the bride.',                              2003),
(43, 'Goodfellas',                  'Three Decades of Life in the Mafia.',               1990),
(44, 'The Godfather',               'An offer you can''t refuse.',                       1972),
(45, 'Scarface',                    'He loved the American Dream. With a vengeance.',     1983),
(46, 'The Silence of the Lambs',    'To enter the mind of a killer she must challenge the mind of a madman.', 1991),
(47, 'Alien',                       'In space no one can hear you scream.',               1979),
(48, 'Aliens',                      'This time it''s war.',                               1986),
(49, 'The Terminator',              'Your future is in its hands.',                       1984),
(50, 'Terminator 2: Judgment Day',  'It''s nothing personal.',                           1991),
(51, 'Total Recall',                'Get ready for the ride of your life.',               1990),
(52, 'Predator',                    'Nothing like it has ever been on earth before.',     1987),
(53, 'Indiana Jones: Raiders',      'The return of the great adventure.',                 1981),
(54, 'Indiana Jones: Last Crusade', 'The man with the hat is back. And this time he''s bringing his dad.', 1989),
(55, 'The Lord of the Rings: FOTR', 'One ring to rule them all.',                         2001),
(56, 'The Lord of the Rings: TTT',  'A new power is rising.',                             2002),
(57, 'The Lord of the Rings: ROTK', 'The eye of the enemy is moving.',                   2003),
(58, 'The Hobbit: An Unexpected Journey', 'From the smallest beginnings come the greatest legends.', 2012),
(59, 'Gladiator',                   'A general who became a slave. A slave who became a gladiator. A gladiator who defied an empire.', 2000),
(60, 'A Beautiful Mind',            'He saw the world in a way no one could have imagined.', 2001),
(61, 'L.A. Confidential',           'Everything is suspect... Everyone is for sale... And nothing is what it seems.', 1997),
(62, 'Fargo',                       'A homespun murder story.',                           1996),
(63, 'No Country for Old Men',      'There are no clean getaways.',                       2007),
(64, 'There Will Be Blood',         'When ambition meets faith.',                         2007),
(65, 'Chinatown',                   'Forget it Jake, it''s Chinatown.',                  1974),
(66, 'Fight Club',                  'Mischief. Mayhem. Soap.',                            1999),
(67, 'Se7en',                       'Seven deadly sins. Seven ways to die.',              1995),
(68, 'The Usual Suspects',          'The greatest trick the devil ever pulled...',        1995),
(69, 'The Sixth Sense',             'Not every gift is a blessing.',                      1999),
(70, 'Unbreakable',                 'Are you ready to discover what keeps you alive?',    2000),
(71, 'Signs',                       'It was never about what was out there.',             2002),
(72, 'Good Will Hunting',           'Some people can''t believe in themselves until someone else believes in them first.', 1997),
(73, 'Dead Poets Society',          'He was their inspiration. He made their lives extraordinary.', 1989),
(74, 'Good Morning Vietnam',        'The wrong man. In the wrong place. At the right time.', 1987),
(75, 'Awakenings',                  'Based on the true story.',                           1990),
(76, 'What''s Eating Gilbert Grape','What''s eating Gilbert Grape?',                     1993),
(77, 'The Revenant',                'Blood lost. Life found.',                            2015),
(78, 'Inception',                   'Your mind is the scene of the crime.',               2010),
(79, 'The Departed',                'Cops or criminals. When you''re facing a loaded gun, what''s the difference?', 2006),
(80, 'Shutter Island',              'Someone is missing.',                                2010),
(81, 'GoodFellas',                  'Three Decades of Life in the Mafia.',               1990),
(82, 'Heat',                        'A Los Angeles crime saga.',                          1995),
(83, 'Taxi Driver',                 'On every street in every city there''s a nobody...',1976),
(84, 'Raging Bull',                 'I never went down, Ray.',                            1980),
(85, 'Untouchables',                'The Chicago mobs. The FBI. One man stood between them.', 1987),
(86, 'Schindler''s List',           'Whoever saves one life, saves the world entire.',    1993),
(87, 'Saving Private Ryan',         'The mission is a man.',                              1998),
(88, 'Catch Me If You Can',         'The true story of a real fake.',                     2002),
(89, 'Munich',                      'The world was watching in 1972. Now the truth can be told.', 2005),
(90, 'Lincoln',                     'His greatest challenge would be to unite a nation.',  2012),
(91, 'GoldenEye',                   'You know the name. You know the number.',            1995),
(92, 'Tomorrow Never Dies',         'Danger is forever.',                                 1997),
(93, 'The World Is Not Enough',     'Danger. Power. Seduction.',                          1999),
(94, 'Die Another Day',             'Danger is forever.',                                 2002),
(95, 'Casino Royale',               'Everyone has a mission.',                            2006),
(96, 'Quantum of Solace',           'The world is not enough.',                           2008),
(97, 'Skyfall',                     'Think on the dead.',                                  2012),
(98, 'Spectre',                     'A criminal organization. A perfect mystery.',         2015),
(99, 'No Time to Die',              'The mission that changes everything begins with trust.', 2021),
(100,'Everything Everywhere All At Once','The universe is so much bigger than you realize.', 2022);

INSERT INTO movie_actors (person_id, movie_id, role) VALUES
(1,  1,  'Neo'),
(2,  1,  'Morpheus'),
(3,  1,  'Trinity'),
(4,  1,  'Agent Smith'),
(1,  2,  'Neo'),
(2,  2,  'Morpheus'),
(3,  2,  'Trinity'),
(4,  2,  'Agent Smith'),
(1,  3,  'Neo'),
(2,  3,  'Morpheus'),
(3,  3,  'Trinity'),
(4,  3,  'Agent Smith'),
(1,  4,  'Kevin Lomax'),
(9,  5,  'Lt. Daniel Kaffee'),
(10, 5,  'Col. Nathan R. Jessep'),
(11, 5,  'Lt. Cdr. JoAnne Galloway'),
(12, 5,  'Capt. Jack Ross'),
(13, 5,  'Lt. Jonathan Kendrick'),
(9,  6,  'Maverick'),
(15, 6,  'Charlie'),
(16, 6,  'Iceman'),
(17, 6,  'Goose'),
(18, 6,  'Viper'),
(9,  7,  'Jerry Maguire'),
(14, 7,  'Rod Tidwell'),
(20, 7,  'Dorothy Boyd'),
(5,  8,  'Gordie Lachance'),
(5,  9,  'Melvin Udall'),
(8,  13, 'Annie Reed'),
(5,  18, 'Chuck Noland'),
(5,  19, 'Jim Lovell'),
(5,  20, 'Paul Edgecomb'),
(5,  21, 'Forrest Gump'),
(6,  21, 'Jenny'),
(7,  21, 'Lt. Dan Taylor'),
(5,  22, 'Andrew Beckett'),
(38, 40, 'Vincent Vega'),
(37, 40, 'Mia Wallace'),
(36, 40, 'Jules Winnfield'),
(39, 40, 'Winston Wolfe'),
(40, 40, 'Pumpkin'),
(41, 40, 'Honey Bunny'),
(42, 40, 'Marsellus Wallace'),
(43, 40, 'Lance'),
(44, 40, 'Jody'),
(45, 40, 'Butch Coolidge'),
(38, 41, 'Mr. Keds'),
(36, 41, 'Ordell Robbie'),
(40, 41, 'Mr. Orange'),
(37, 42, 'The Bride'),
(50, 43, 'Jimmy Conway'),
(51, 43, 'Henry Hill'),
(52, 43, 'Tommy DeVito'),
(53, 43, 'Karen Hill'),
(54, 43, 'Paul Cicero'),
(48, 44, 'Michael Corleone'),
(50, 44, 'Vito Corleone'),
(52, 44, 'Fredo Corleone'),
(48, 45, 'Tony Montana'),
(73, 46, 'Dr. Hannibal Lecter'),
(74, 46, 'Clarice Starling'),
(75, 46, 'Jack Crawford'),
(76, 46, 'Buffalo Bill'),
(55, 47, 'Ellen Ripley'),
(72, 47, 'Kane'),
(57, 47, 'Ash'),
(55, 48, 'Ellen Ripley'),
(56, 48, 'Corporal Hicks'),
(57, 48, 'Bishop'),
(58, 48, 'Private Hudson'),
(59, 49, 'The Terminator'),
(60, 49, 'Sarah Connor'),
(56, 49, 'Kyle Reese'),
(59, 51, 'Douglas Quaid'),
(59, 52, 'Major Alan Schaefer'),
(63, 53, 'Indiana Jones'),
(63, 54, 'Indiana Jones'),
(64, 54, 'Professor Henry Jones'),
(66, 55, 'Gandalf'),
(67, 55, 'Frodo Baggins'),
(68, 55, 'Legolas'),
(69, 55, 'Aragorn'),
(70, 55, 'Arwen'),
(71, 55, 'Gollum'),
(65, 55, 'Galadriel'),
(66, 56, 'Gandalf'),
(67, 56, 'Frodo Baggins'),
(68, 56, 'Legolas'),
(69, 56, 'Aragorn'),
(71, 56, 'Gollum'),
(66, 57, 'Gandalf'),
(67, 57, 'Frodo Baggins'),
(69, 57, 'Aragorn'),
(71, 57, 'Gollum'),
(26, 59, 'Maximus'),
(27, 59, 'Commodus'),
(28, 59, 'Lucilla'),
(29, 59, 'Proximo'),
(26, 60, 'John Nash'),
(21, 72, 'Will Hunting'),
(23, 72, 'Sean Maguire'),
(22, 72, 'Chuckie Sullivan'),
(24, 72, 'Skylar'),
(25, 72, 'Prof. Gerald Lambeau'),
(23, 73, 'John Keating'),
(23, 74, 'Adrian Cronauer'),
(30, 66, 'Tyler Durden'),
(31, 66, 'The Narrator'),
(32, 66, 'Marla Singer'),
(33, 66, 'Robert Paulson'),
(34, 66, 'Angel Face'),
(35, 67, 'David Mills'),
(46, 67, 'William Somerset'),
(35, 69, 'Malcolm Crowe'),
(35, 70, 'David Dunn'),
(82, 67, 'John Doe'),
(46, 63, 'Ed Tom Bell'),
(91, 91, 'James Bond'),
(92, 91, 'Wai Lin'),
(93, 91, 'Carver'),
(91, 92, 'James Bond'),
(94, 93, 'Christmas Jones'),
(95, 95, 'Yelena'),
(96, 97, 'Moneypenny'),
(97, 93, 'Elektra King'),
(98, 93, 'Renard'),
(99, 93, 'Christmas Jones'),
(100,91, 'M');
